const assert = require('node:assert/strict');
const fs = require('node:fs');

const app = fs.readFileSync(require.resolve('../app.js'), 'utf8');
const index = fs.readFileSync(require.resolve('../index.html'), 'utf8');
const sw = fs.readFileSync(require.resolve('../sw.js'), 'utf8');
const style = fs.readFileSync(require.resolve('../style.css'), 'utf8');

assert.equal((app.match(/function form\(id,prefill\)/g) || []).length, 1);
assert.match(app, /function openAISuggestions\(\)/);
assert.match(app, /function previewSuggestion\(recipe\)/);
assert.match(app, /Ver receita/);
assert.match(app, /Salvar esta receita/);
assert.match(app, /form\(null,recipe\)/);
assert.match(app, /MemoriasAI\.suggestRecipes\(query/);
assert.match(app, /const endpoint=window\.MEMORIAS_PROXY_URL\|\|''/);
assert.match(app, /id="aiSuggestStatus" aria-live="polite"/);
assert.match(app, /id="aiSuggestionResults"[^>]*aria-live="polite"/);
assert.match(app, /\['#ocrModal','#formModal','#detailModal','#aiSuggestModal'\]/);
assert.match(app, /role="dialog" aria-modal="true" aria-labelledby=/);
assert.match(app, /activeRecognition=null/);
assert.match(app, /async function releaseWake\(\)/);
assert.match(app, /MemoriasAssistant\.scaleIngredients/);
assert.match(app, /MemoriasAssistant\.buildShoppingList/);
assert.match(app, /MemoriasAssistant\.suggestSubstitution/);
assert.match(app, /MemoriasAssistant\.adaptCookingMethod/);
assert.match(app, /navigator\.(share|clipboard)/);
assert.match(app, /window\.print\(\)/);
assert.match(app, /id="ocrFiles" type="file" accept="image\/\*" capture="environment" multiple/);
assert.match(app, /aria-live="polite"/);
assert.match(app, /MemoriasDB\.putDraft/);
assert.match(app, /MemoriasDB\.deleteDraft/);
assert.match(app, /MAX_BACKUP_PHOTO_DATA_SIZE/);
assert.match(app, /isSafePhotoData/);
assert.match(app, /URL\.revokeObjectURL\(url\)/);
assert.match(app, /save\.disabled=true/);
assert.match(app, /finally\{save\.disabled=false\}/);
assert.doesNotMatch(app, /api[_-]?key/i);

assert.match(index, /id="aiSuggest"/);
assert.match(index, /Encontrar uma receita/);
assert.match(index, /id="search"/);
assert.match(index, /id="aiImport"/);
assert.match(index, /Foto de receita/);
assert.match(index, /id="restoreButton"/);
assert.match(index, /id="aiSuggestModal" class="modal hide"/);
assert.match(index, /Content-Security-Policy/);
assert.match(sw, /memorias-a-mesa-v[0-9]+/);
assert.match(sw, /"\.\/ai-adapter\.js"/);
assert.match(sw, /"\.\/assistant\.js"/);
assert.match(style, /prefers-reduced-motion/);
assert.match(style, /\.welcome/);
assert.match(style, /\.kitchen-illustration/);
assert.match(style, /button:focus-visible/);

console.log('app.test.js: ok');
