'use strict';
// Servidor opcional: a chave Gemini fica SOMENTE neste processo.
const http=require('node:http');
const key=process.env.GEMINI_API_KEY;
const model=process.env.GEMINI_MODEL||'gemini-3.6-flash';
const port=Number(process.env.PORT||8787);
if(!key)throw new Error('Defina GEMINI_API_KEY antes de iniciar o proxy.');
const send=(res,status,data)=>res.writeHead(status,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':process.env.CORS_ORIGIN||'*'}).end(JSON.stringify(data));
http.createServer(async(req,res)=>{if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':process.env.CORS_ORIGIN||'*','access-control-allow-methods':'POST, OPTIONS','access-control-allow-headers':'content-type'}).end();return}if(req.method!=='POST'||req.url!=='/suggestions')return send(res,404,{error:'Não encontrado.'});let raw='';req.on('data',part=>{raw+=part;if(raw.length>12000)req.destroy()});req.on('end',async()=>{try{const body=JSON.parse(raw||'{}'),query=String(body.query||'').trim().slice(0,200),maxResults=Math.max(1,Math.min(5,Number(body.maxResults)||3));if(query.length<3)return send(res,400,{error:'Busca muito curta.'});const prompt=`Crie até ${maxResults} receitas brasileiras ou internacionais para: ${query}. Responda APENAS JSON: {"suggestions":[{"title":"","category":"","time":30,"servings":4,"difficulty":"Fácil","ingredients":[{"qty":"","unit":"","name":""}],"steps":[""],"tips":""}]}. Cada sugestão deve ser uma receita completa e específica; não invente substitutos genéricos.`;const api=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json'}})});if(!api.ok)return send(res,502,{error:'A busca online não respondeu.'});const data=await api.json(),text=data.candidates&&data.candidates[0]&&data.candidates[0].content&&data.candidates[0].content.parts&&data.candidates[0].content.parts[0]&&data.candidates[0].content.parts[0].text;const answer=JSON.parse(text||'{}');return send(res,200,{suggestions:Array.isArray(answer.suggestions)?answer.suggestions:[]})}catch(_){return send(res,400,{error:'Não consegui entender a busca.'})}})}).listen(port,()=>console.log(`Proxy de receitas em http://localhost:${port}/suggestions`));
